[package]
name = "caching_ext"
edition = "2018"
version = "0.1.0"
authors = ['Facebook']
license = "GPLv2+"
include = ["src/**/*.rs"]

[dependencies]
mononoke_types = { path = "../../../mononoke_types" }
cachelib = { git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
cloned = { git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
futures_ext = { git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
memcache = { git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
anyhow = "1.0"
bytes = { version = "0.5", features = ["serde"] }
futures = "0.1"
tokio = "0.1"

[dev-dependencies]
maplit = "1.0"
quickcheck = "0.9"
tokio-compat = "0.1"
