[package]
name = "pyworker"
version = "0.1.0"
edition = "2018"

[features]
default = []
python2 = ["cpython/python27-sys", "cpython_ext/python2"]
python3 = ["cpython/python3-sys", "cpython_ext/python3"]

[dependencies]
anyhow = "1.0.20"
pyrevisionstore = { path = "../pyrevisionstore" }
crossbeam = "0.7"
revisionstore = { path = "../../../../lib/revisionstore" }
cpython_ext = { path = "../../../../lib/cpython-ext", default-features = false }
cpython = { version = "0.5", default-features = false }
minibytes = { path = "../../../../lib/minibytes" }
types = { path = "../../../../lib/types" }
tracing = "0.1"
vfs = { path = "../../../../lib/vfs" }

[dev-dependencies]
tempfile = "3.1"
quickcheck = "0.9"
types = { path = "../../../../lib/types", default-features = false, features = ["for-tests"] }
revisionstore = { path = "../../../../lib/revisionstore", default-features = false, features = ["for-tests"] }
memmap = "0.7"
