[package]
name = "throttledblob"
edition = "2018"
version = "0.1.0"
authors = ['Facebook']
license = "GPLv2+"
include = ["src/*.rs"]

[dependencies]
async_limiter = { path = "../../common/async_limiter" }
blobstore = { path = ".." }
context = { path = "../../server/context" }
mononoke_types = { path = "../../mononoke_types" }
anyhow = "1.0"
futures = { version = "0.3.5", features = ["async-await", "compat"] }
ratelimit_meter = "5"
