[package]
name = "pyexchange"
version = "0.1.0"
edition = "2021"

[dependencies]
cpython_ext = { path = "../../../../lib/cpython-ext" }
cpython = { version = "0.7", default-features = false }
exchange = { path = "../../../../lib/exchange" }
pyedenapi = { path = "../pyedenapi" }
pydag = { path = "../pydag" }
pymetalog = { path = "../pymetalog" }

