[package]
name = "mercurial_bundles"
version = "0.0.1"
authors = ["Facebook"]
license = "GPLv2+"
edition = "2018"

[dependencies]
ascii = "0.8.6"
byteorder = "1.1.0"
bytes = "0.4.5"
error-chain = "0.11.0"
futures = "0.1.17"
lazy_static = "0.2.10"
slog = "2.0.12"
tokio-io = "0.1.4"
tokio-proto = "0.1.1"
url = "1.6.0"

async-compression = { path = "../async-compression" }
