[package]
name = "blobstore_factory"
edition = "2018"
version = "0.1.0"
authors = ['Facebook']
license = "GPLv2+"
include = ["src/**/*.rs"]

[dependencies]
blobstore = { path = ".." }
blobstore_sync_queue = { path = "../../blobstore_sync_queue" }
cacheblob = { path = "../cacheblob" }
chaosblob = { path = "../chaosblob" }
fileblob = { path = "../fileblob" }
logblob = { path = "../logblob" }
memblob = { path = "../memblob" }
metaconfig_types = { path = "../../metaconfig/types" }
multiplexedblob = { path = "../multiplexedblob" }
packblob = { path = "../packblob" }
prefixblob = { path = "../prefixblob" }
readonlyblob = { path = "../readonlyblob" }
sql_construct = { path = "../../common/sql_construct" }
sql_ext = { path = "../../common/rust/sql_ext" }
sqlblob = { path = "../sqlblob" }
throttledblob = { path = "../throttledblob" }
fbinit = { git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
futures_ext = { git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
scuba = { git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
sql = { git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
anyhow = "1.0"
futures = { version = "0.3", features = ["async-await", "compat"] }
futures-old = { package = "futures", version = "0.1" }
slog = { version = "2.5", features = ["max_level_debug"] }
