[package]
name = "pyrenderdag"
version = "0.1.0"
edition = "2021"

[dependencies]
cpython = { version = "0.7", default-features = false }
cpython_ext = { path = "../../../../lib/cpython-ext" }
minibytes = { path = "../../../../lib/minibytes" }
renderdag = { path = "../../../../lib/renderdag" }
parking_lot = "0.11.2"

