[package]
name = "mononoke_types-thrift"
edition = "2018"
version = "0.1.0"
authors = ['Facebook']
license = "GPLv2+"
include = ["thrift_lib.rs"]
build = "thrift_build.rs"

[lib]
path = "thrift_lib.rs"

[build-dependencies]
thrift_compiler = { git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }

[dependencies]
codegen_includer_proc_macro = { git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
fbthrift = { git = "https://github.com/facebook/fbthrift.git", branch = "master" }
anyhow = "1.0"
async-trait = { version = "0.1", features = ["support_old_nightly"] }
futures = "0.1" # todo: rename to "futures-old"
futures-preview = { package = "futures", version = "0.3", features = ["async-await", "compat"] } # todo: rename to "futures"
lazy_static = "1.0"
serde = { version = "1.0", features = ["derive", "rc"] }
serde_derive = "1.0"
thiserror = "1.0"
