[package]
name = "pydirs"
version = "0.1.0"
edition = "2021"

[features]
default = []
python3 = ["cpython/python3-sys", "cpython_ext/python3"]

[dependencies]
cpython_ext = { path = "../../../../lib/cpython-ext", default-features = false }
cpython = { version = "0.7", default-features = false }
encoding = { path = "../../../../lib/encoding" }
