[package]
name = "pyregex"
version = "0.1.0"
edition = "2021"

[dependencies]
cpython = { version = "0.7", default-features = false }
cpython_ext = { path = "../../../../lib/cpython-ext", default-features = false }
regex = "1"

[features]
default = []
python3 = ["cpython/python3-sys", "cpython_ext/python3"]
