[package]
name = "pynodemap"
version = "0.1.0"
edition = "2018"

[dependencies]
cpython = { version = "0.5", default-features = false }
cpython-ext = { path = "../../../../lib/cpython-ext", default-features = false }
nodemap = { path = "../../../../lib/nodemap" }
types = { path = "../../../../lib/types" }
