[package]
name = "bindings"
version = "0.1.0"
edition = "2021"

[lib]
name = "bindings"

[profile.release]
debug = true
incremental = true
lto = false

[dependencies]
cpython_ext = { path = "../../lib/cpython-ext" }
cpython = { version = "0.7", default-features = false }
paste = "1.0"
# see update_modules.sh
# [[[cog
# import cog, glob, os
# for path in sorted(glob.glob('modules/py*/TARGETS')):
#     name = os.path.basename(os.path.dirname(path))
#     cog.outl(f'{name} = {{ path = "modules/{name}" }}')
# ]]]
pyauth = { path = "modules/pyauth" }
pyblackbox = { path = "modules/pyblackbox" }
pybytes = { path = "modules/pybytes" }
pycats = { path = "modules/pycats" }
pycheckout = { path = "modules/pycheckout" }
pyclientinfo = { path = "modules/pyclientinfo" }
pycliparser = { path = "modules/pycliparser" }
pyconfigloader = { path = "modules/pyconfigloader" }
pydag = { path = "modules/pydag" }
pydiffhelpers = { path = "modules/pydiffhelpers" }
pydirs = { path = "modules/pydirs" }
pydoctor = { path = "modules/pydoctor" }
pydrawdag = { path = "modules/pydrawdag" }
pyeagerepo = { path = "modules/pyeagerepo" }
pyedenapi = { path = "modules/pyedenapi" }
pyerror = { path = "modules/pyerror" }
pyexchange = { path = "modules/pyexchange" }
pyfail = { path = "modules/pyfail" }
pyfs = { path = "modules/pyfs" }
pygitstore = { path = "modules/pygitstore" }
pyhgmetrics = { path = "modules/pyhgmetrics" }
pyhgtime = { path = "modules/pyhgtime" }
pyidentity = { path = "modules/pyidentity" }
pyindexedlog = { path = "modules/pyindexedlog" }
pyio = { path = "modules/pyio" }
pylock = { path = "modules/pylock" }
pylz4 = { path = "modules/pylz4" }
pymanifest = { path = "modules/pymanifest" }
pymetalog = { path = "modules/pymetalog" }
pymutationstore = { path = "modules/pymutationstore" }
pynodemap = { path = "modules/pynodemap" }
pypathhistory = { path = "modules/pypathhistory" }
pypathmatcher = { path = "modules/pypathmatcher" }
pypprint = { path = "modules/pypprint" }
pyprocess = { path = "modules/pyprocess" }
pyprogress = { path = "modules/pyprogress" }
pyrefencode = { path = "modules/pyrefencode" }
pyregex = { path = "modules/pyregex" }
pyrenderdag = { path = "modules/pyrenderdag" }
pyrepo = { path = "modules/pyrepo" }
pyrevisionstore = { path = "modules/pyrevisionstore" }
pyrevlogindex = { path = "modules/pyrevlogindex" }
pysptui = { path = "modules/pysptui" }
pystatus = { path = "modules/pystatus" }
pythreading = { path = "modules/pythreading" }
pytracing = { path = "modules/pytracing" }
pytreestate = { path = "modules/pytreestate" }
pyvlq = { path = "modules/pyvlq" }
pyworker = { path = "modules/pyworker" }
pyworkingcopy = { path = "modules/pyworkingcopy" }
pyzstd = { path = "modules/pyzstd" }
pyzstore = { path = "modules/pyzstore" }
# [[[end]]]
