[package]
name = "pyconfigparser"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
configparser = { path = "../../../../lib/config/parser" }
cpython = { version = "0.7", default-features = false }
cpython_ext = { path = "../../../../lib/cpython-ext", default-features = false }
util = { path = "../../../../lib/util" }
version = { path = "../../../../lib/version" }

[features]
python2 = ["cpython/python27-sys", "cpython_ext/python2"]
python3 = ["cpython/python3-sys", "cpython_ext/python3"]
