[package]
name = "mononoke_hg_sync_job_helper_lib"
version = "0.1.0"
authors = ["Facebook"]
edition = "2018"
license = "GPLv2+"

[lib]
path = "helper_lib/lib.rs"

[[bin]]
name = "mononoke_hg_sync_job"
path = "src/main.rs"

[dependencies]
anyhow = "1.0"
async-stream = "0.3"
base64 = "0.11.0"
blobrepo = { version = "0.1.0", path = "../blobrepo" }
blobrepo_hg = { version = "0.1.0", path = "../blobrepo/blobrepo_hg" }
blobstore = { version = "0.1.0", path = "../blobstore" }
bonsai_globalrev_mapping = { version = "0.1.0", path = "../bonsai_globalrev_mapping" }
bookmarks = { version = "0.1.0", path = "../bookmarks" }
borrowed = { version = "0.1.0", git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
bytes = { version = "0.5", features = ["serde"] }
bytes-old = { package = "bytes", version = "0.4", features = ["serde"] }
cached_config = { version = "0.1.0", git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
clap = "2.33"
cloned = { version = "0.1.0", git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
cmdlib = { version = "0.1.0", path = "../cmdlib" }
context = { version = "0.1.0", path = "../server/context" }
dbbookmarks = { version = "0.1.0", path = "../bookmarks/dbbookmarks" }
fbinit = { version = "0.1.0", git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
filestore = { version = "0.1.0", path = "../filestore" }
futures = { version = "0.3.13", features = ["async-await", "compat"] }
futures-old = { package = "futures", version = "0.1.31" }
futures_01_ext = { version = "0.1.0", git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
futures_ext = { version = "0.1.0", git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
futures_stats = { version = "0.1.0", git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
futures_watchdog = { version = "0.1.0", path = "../common/futures_watchdog" }
getbundle_response = { version = "0.1.0", path = "../repo_client/getbundle_response" }
gotham_ext = { version = "0.1.0", path = "../gotham_ext" }
hgserver_config = { version = "0.1.0", path = "../../../configerator/structs/scm/mononoke/hgserverconf" }
http = "0.2"
hyper = "0.13.10"
hyper-openssl = "0.8"
itertools = "0.8"
lfs_protocol = { version = "0.1.0", path = "../lfs_protocol" }
maplit = "1.0"
mercurial_bundle_replay_data = { version = "0.1.0", path = "../mercurial/bundle_replay_data" }
mercurial_bundles = { version = "0.1.0", path = "../mercurial/bundles" }
mercurial_revlog = { version = "0.1.0", path = "../mercurial/revlog" }
mercurial_types = { version = "0.1.0", path = "../mercurial/types" }
metaconfig_types = { version = "0.1.0", path = "../metaconfig/types" }
mononoke_types = { version = "0.1.0", path = "../mononoke_types" }
mutable_counters = { version = "0.1.0", path = "../mutable_counters" }
pin-project = "0.4"
reachabilityindex = { version = "0.1.0", path = "../reachabilityindex" }
regex = "1.4.2"
repo_read_write_status = { version = "0.1.0", path = "../repo_client/repo_read_write_status" }
revset = { version = "0.1.0", path = "../revset" }
scuba_ext = { version = "0.1.0", path = "../common/scuba_ext" }
serde_json = { version = "1.0", features = ["float_roundtrip"] }
shared_error = { version = "0.1.0", git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
skiplist = { version = "0.1.0", path = "../reachabilityindex/skiplist" }
slog = { version = "2.5", features = ["max_level_debug"] }
sql = { version = "0.1.0", git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
sql_construct = { version = "0.1.0", path = "../common/sql_construct" }
sql_ext = { version = "0.1.0", path = "../common/rust/sql_ext" }
tempfile = "3.1"
thiserror = "1.0"
tokio = { version = "0.2.25", features = ["full", "test-util"] }

[dev-dependencies]
assert_matches = "1.5"
fbinit-tokio-02 = { version = "0.1.0", git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
memblob = { version = "0.1.0", path = "../blobstore/memblob" }
mercurial_types-mocks = { version = "0.1.0", path = "../mercurial/types/mocks" }
mononoke_types-mocks = { version = "0.1.0", path = "../mononoke_types/mocks" }
test_repo_factory = { version = "0.1.0", path = "../repo_factory/test_repo_factory" }
tests_utils = { version = "0.1.0", path = "../tests/utils" }

[patch.crates-io]
addr2line = { git = "https://github.com/gimli-rs/addr2line.git", rev = "0b6b6018b5b252a18e628fba03885f7d21844b3c" }
bytecount = { git = "https://github.com/llogiq/bytecount", rev = "469eaf8395c99397cd64d059737a9054aa014088" }
chashmap = { git = "https://gitlab.redox-os.org/ahornby/chashmap", rev = "901ace2ca3cdbc2095adb1af111d211e254e2aae" }
const-random = { git = "https://github.com/fbsource/const-random", rev = "374c5b46427fe2ffbf6acbd9c1687e0f1a809f95" }
curl = { git = "https://github.com/kulshrax/curl-rust", rev = "2a15bbd8dbbd54734313fa703a64db7ce6ddaff0" }
curl-sys = { git = "https://github.com/kulshrax/curl-rust", rev = "2a15bbd8dbbd54734313fa703a64db7ce6ddaff0" }
enumset = { git = "https://github.com/danobi/enumset", rev = "4c01c583c27a725948fededbfb3461c572a669a4" }
gotham-02 = { package = "gotham", git = "https://github.com/krallin/gotham-02.git", rev = "1eb3b976c31e7e4334b188f3abfa5cc2e5cae033" }
gotham_derive-02 = { package = "gotham_derive", git = "https://github.com/krallin/gotham-02.git", rev = "1eb3b976c31e7e4334b188f3abfa5cc2e5cae033" }
hyper-02 = { package = "hyper", version = "0.13.10", git = "https://github.com/krallin/hyper-02.git", rev = "9c9453c5ae3e92de4ba30edd81bb45371b8fa8d6" }
lru-disk-cache = { git = "https://github.com/mozilla/sccache", rev = "033ebaae69beeb0ac04e8c35d6ff1103487bd9a3" }
openssl = { git = "https://github.com/sfackler/rust-openssl", rev = "68fc8ba890d77986b06ca5ce29d1089285fbbcf9" }
openssl-sys = { git = "https://github.com/sfackler/rust-openssl", rev = "68fc8ba890d77986b06ca5ce29d1089285fbbcf9" }
petgraph = { git = "https://github.com/jkeljo/petgraph", rev = "e3e9dd8632d23973fdc0b42c1117d5e5fc5fa384" }
prost = { git = "https://github.com/gabrielrussoc/prost", branch = "protoc-runtime" }
prost-build = { git = "https://github.com/gabrielrussoc/prost", branch = "protoc-runtime" }
prost-derive = { git = "https://github.com/gabrielrussoc/prost", branch = "protoc-runtime" }
prost-types = { git = "https://github.com/gabrielrussoc/prost", branch = "protoc-runtime" }
r2d2_sqlite = { git = "https://github.com/jsgf/r2d2-sqlite.git", rev = "6d77a828ca0a3c507a3f58561532a1b6c66c7918" }
rustfilt = { git = "https://github.com/jsgf/rustfilt.git", rev = "8141fa7f1caee562ee8daffb2ddeca3d1f0d36e5" }
tokio-02 = { package = "tokio", version = "0.2.25", git = "https://github.com/krallin/tokio.git", rev = "818f943db36e32b7c928351c32fe69ac913409f9" }
tokio-compat = { package = "tokio-compat", version = "0.1.6", git = "https://github.com/krallin/tokio-compat.git", rev = "c2330c2a0141353e467cc5861988daa2eae7cb54" }
tokio-core = { git = "https://github.com/bolinfest/tokio-core", rev = "5f37aa3c627d56ee49154bc851d6930f5ab4398f" }
toml = { git = "https://github.com/jsgf/toml-rs", branch = "dotted-table-0.5.7" }
