[package]
name = "benchmark_lib"
edition = "2018"
version = "0.1.0"
authors = ['Facebook']
license = "GPLv2+"
include = ["benchmark.rs", "lib/**/*.rs"]

[lib]
path = "lib/lib.rs"

[[bin]]
name = "benchmark"
path = "benchmark.rs"

[dependencies]
blobrepo = { path = "../blobrepo" }
blobrepo_factory = { path = "../blobrepo/factory" }
blobrepo_hg = { path = "../blobrepo/blobrepo_hg" }
blobstore = { path = "../blobstore" }
bonsai_git_mapping = { path = "../bonsai_git_mapping" }
bonsai_globalrev_mapping = { path = "../bonsai_globalrev_mapping" }
bonsai_hg_mapping = { path = "../bonsai_hg_mapping" }
cacheblob = { path = "../blobstore/cacheblob" }
changesets = { path = "../changesets" }
cmdlib = { path = "../cmdlib" }
context = { path = "../server/context" }
dbbookmarks = { path = "../bookmarks/dbbookmarks" }
delayblob = { path = "../blobstore/delayblob" }
derived_data = { path = "../derived_data" }
filenodes = { path = "../filenodes" }
filestore = { path = "../filestore" }
fsnodes = { path = "../derived_data/fsnodes" }
memblob = { path = "../blobstore/memblob" }
mercurial_mutation = { path = "../mercurial/mutation" }
mercurial_types = { path = "../mercurial/types" }
mononoke_types = { path = "../mononoke_types" }
newfilenodes = { path = "../newfilenodes" }
phases = { path = "../phases" }
repo_blobstore = { path = "../blobrepo/repo_blobstore" }
scuba_ext = { path = "../common/scuba_ext" }
sql_construct = { path = "../common/sql_construct" }
unodes = { path = "../derived_data/unodes" }
cachelib = { git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
fbinit = { git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
futures_ext = { git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
futures_stats = { git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
anyhow = "1.0"
clap = "2.33"
futures = { version = "0.3", features = ["async-await", "compat"] }
futures-old = { package = "futures", version = "0.1" }
rand = { version = "0.7", features = ["small_rng"] }
rand_distr = "0.2"
rand_xorshift = "0.2"
tokio-compat = "0.1"
tokio-timer = "0.2"
