[package]
name = "blobrepo_utils"
edition = "2018"
version = "0.1.0"
authors = ['Facebook']
license = "GPLv2+"
include = ["src/**/*.rs", "test/**/*.rs"]

[lib]
path = "src/lib.rs"

[[test]]
name = "blobrepo_utils_test"
path = "test/main.rs"

[dependencies]
blobrepo = { path = "../blobrepo" }
blobstore = { path = "../blobstore" }
cacheblob = { path = "../blobstore/cacheblob" }
context = { path = "../server/context" }
manifest = { path = "../manifest" }
mercurial_types = { path = "../mercurial/types" }
mononoke_types = { path = "../mononoke_types" }
cloned = { git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
futures_ext = { git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
anyhow = "1.0"
chashmap = "2.2"
futures = "0.1"
slog = { version="2.5", features=["max_level_debug"] }
thiserror = "1.0"
tokio = "0.1"

[dev-dependencies]
fixtures = { path = "../tests/fixtures" }
async_unit = { git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
fbinit = { git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
