[package]
name = "pyedenapi"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = "1.0"
async-runtime = { path = "../../../../lib/async-runtime" }
cpython_async = { path = "../../../../lib/cpython-async", default-features = false }
cpython_ext = { path = "../../../../lib/cpython-ext", default-features = false }
cpython = { version = "0.5", default-features = false }
dag-types = { path = "../../../../lib/dag/dag-types" }
edenapi = { path = "../../../../lib/edenapi" }
edenapi_types = { path = "../../../../lib/edenapi/types" }
futures = { version = "0.3.5", features = ["async-await", "compat"] }
progress = { path = "../../../../lib/progress" }
pyconfigparser = { path = "../pyconfigparser" }
pyprogress = { path = "../pyprogress" }
pyrevisionstore = { path = "../pyrevisionstore" }
revisionstore = { path = "../../../../lib/revisionstore" }
types = { path = "../../../../lib/types" }
version = { path = "../../../../lib/version" }

[features]
default = []
python2 = ["cpython/python27-sys", "cpython_ext/python2", "cpython_async/python2"]
python3 = ["cpython/python3-sys", "cpython_ext/python3", "cpython_async/python3"]
