[package]
name = "pyedenapi"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
async-runtime = { path = "../../../../lib/async-runtime" }
blake2 = "0.9"
cpython_async = { path = "../../../../lib/cpython-async", default-features = false }
cpython_ext = { path = "../../../../lib/cpython-ext" }
cpython = { version = "0.7", default-features = false }
dag-types = { path = "../../../../lib/dag/dag-types" }
edenapi = { path = "../../../../lib/edenapi" }
edenapi_ext = { path = "../../../../lib/edenapi/ext" }
edenapi_types = { path = "../../../../lib/edenapi/types" }
futures = { version = "0.3.5", features = ["async-await", "compat"] }
minibytes = { path = "../../../../lib/minibytes" }
progress-model = { path = "../../../../lib/progress/model" }
pyconfigloader = { path = "../pyconfigloader" }
pyprogress = { path = "../pyprogress" }
pyrevisionstore = { path = "../pyrevisionstore" }
revisionstore = { path = "../../../../lib/revisionstore" }
types = { path = "../../../../lib/types" }

