[package]
name = "reachabilityindex"
edition = "2018"
version = "0.1.0"
authors = ['Facebook']
license = "GPLv2+"
include = ["src/**/*.rs"]

[dependencies]
blobrepo_errors = { path = "../blobrepo/errors" }
changeset_fetcher = { path = "../blobrepo/changeset_fetcher" }
context = { path = "../server/context" }
mononoke_types = { path = "../mononoke_types" }
uniqueheap = { path = "../common/uniqueheap" }
anyhow = "1.0"
async-trait = "0.1.29"
futures-util = "0.3"
maplit = "1.0"
thiserror = "1.0"
