[package]
name = "bounded_traversal"
edition = "2018"
version = "0.1.0"
authors = ['Facebook']
license = "GPLv2+"
include = ["src/**/*.rs"]

[dependencies]
futures = { version = "0.3", features = ["async-await", "compat"] }

[dev-dependencies]
lock_ext = { git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
anyhow = "1.0"
maplit = "1.0"
pretty_assertions = "0.6"
tokio = { version = "=0.2.13", features = ["full"] }
