[workspace]

members = [
    "backsyncer",
    "benchmark",
    "blobimport_lib",
    "blobrepo",
    "blobrepo/blobsync",
    "blobrepo/changeset_fetcher",
    "blobrepo/errors",
    "blobrepo/factory",
    "blobrepo/repo_blobstore",
    "blobrepo_utils",
    "blobstore",
    "blobstore/cacheblob",
    "blobstore/chaosblob",
    "blobstore/context_concurrency_blobstore",
    "blobstore/delayblob",
    "blobstore/factory",
    "blobstore/fileblob",
    "blobstore/if",
    "blobstore/memblob",
    "blobstore/multiplexedblob",
    "blobstore/prefixblob",
    "blobstore/readonlyblob",
    "blobstore/redactedblobstore",
    "blobstore/samplingblob",
    "blobstore/sqlblob",
    "blobstore/sqlblob/if",
    "blobstore/throttledblob",
    "blobstore_sync_queue",
    "bonsai_git_mapping",
    "bonsai_git_mapping/git_mapping_pushrebase_hook",
    "bonsai_globalrev_mapping",
    "bonsai_globalrev_mapping/globalrev_pushrebase_hook",
    "bonsai_hg_mapping",
    "bonsai_hg_mapping/if",
    "bookmarks",
    "bookmarks/bookmarks_types",
    "bookmarks/dbbookmarks",
    "bookmarks/warm_bookmarks_cache",
    "bulkops",
    "cache_warmup",
    "changesets",
    "changesets/if",
    "cmdlib",
    "cmdlib/x_repo",
    "commit_rewriting/bookmark_renaming",
    "commit_rewriting/cross_repo_sync",
    "commit_rewriting/cross_repo_sync/test_utils",
    "commit_rewriting/movers",
    "commit_rewriting/synced_commit_mapping",
    "common/allocation_tracing",
    "common/async_limiter",
    "common/async_limiter/examples/tokio_v1",
    "common/async_limiter/examples/tokio_v2",
    "common/bounded_traversal",
    "common/dedupmap",
    "common/rust/caching_ext",
    "common/rust/slog_ext",
    "common/rust/sql_ext",
    "common/scuba_ext",
    "common/sql_construct",
    "common/topo_sort",
    "common/uniqueheap",
    "derived_data",
    "derived_data/blame",
    "derived_data/changeset_info",
    "derived_data/changeset_info/if",
    "derived_data/deleted_files_manifest",
    "derived_data/fastlog",
    "derived_data/filenodes",
    "derived_data/fsnodes",
    "derived_data/mercurial_derived_data",
    "derived_data/unodes",
    "derived_data/utils",
    "fastreplay",
    "filenodes",
    "filenodes/if",
    "filestore",
    "git/git_types",
    "git/git_types/if",
    "git/gitimport",
    "hgproto",
    "hook_tailer",
    "hooks",
    "hooks/content-stores",
    "lfs_import_lib",
    "lfs_protocol",
    "load_limiter",
    "manifest",
    "manifest/test_utils",
    "megarepolib",
    "mercurial/bundles",
    "mercurial/mutation",
    "mercurial/revlog",
    "mercurial/types",
    "mercurial/types/if",
    "mercurial/types/mocks",
    "metaconfig/parser",
    "metaconfig/types",
    "microwave",
    "microwave/builder",
    "microwave/if",
    "mononoke_types",
    "mononoke_types/if",
    "mononoke_types/mocks",
    "mutable_counters",
    "newfilenodes",
    "permission_checker",
    "phases",
    "pushrebase",
    "reachabilityindex",
    "reachabilityindex/common",
    "reachabilityindex/if",
    "reachabilityindex/skiplist",
    "reachabilityindex/test-helpers",
    "repo_client",
    "repo_client/getbundle_response",
    "repo_client/mononoke_repo",
    "repo_client/obsolete",
    "repo_client/remotefilelog",
    "repo_client/repo_read_write_status",
    "repo_client/reverse_filler_queue",
    "repo_client/scribe_commit_queue",
    "repo_client/streaming_clone",
    "repo_client/unbundle",
    "repo_client/wirepack",
    "revset",
    "revset/revset-test-helper",
    "server",
    "server/context",
    "server/monitoring",
    "server/repo_listener",
    "server/session_id",
    "sshrelay",
    "tests/fixtures",
    "tests/utils",
    "tests/write_stub_log_entry",
    "time_window_counter",
    "tunables",
    "tunables/tunables-derive",
    "unbundle_replay",
]
