[package]
name = "mutable_counters"
edition = "2018"
version = "0.1.0"
authors = ['Facebook']
license = "GPLv2+"
include = ["schemas/**/*.sql", "src/**/*.rs", "test/**/*.rs"]

[lib]
path = "src/lib.rs"

[[test]]
name = "mutable_counters_test"
path = "test/main.rs"

[dependencies]
context = { path = "../server/context" }
mononoke_types = { path = "../mononoke_types" }
sql_construct = { path = "../common/sql_construct" }
sql_ext = { path = "../common/rust/sql_ext" }
futures_ext = { git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
sql = { git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
anyhow = "1.0"
futures = "0.1"

[dev-dependencies]
mononoke_types-mocks = { path = "../mononoke_types/mocks" }
async_unit = { git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
fbinit = { git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
tokio = "0.1"
tokio-compat = "0.1"
