[package]
name = "fsnodes"
edition = "2018"
version = "0.1.0"
authors = ['Facebook']
license = "GPLv2+"
include = ["*.rs"]

[lib]
path = "lib.rs"

[dependencies]
blobrepo = { path = "../../blobrepo" }
blobstore = { path = "../../blobstore" }
context = { path = "../../server/context" }
derived_data = { path = ".." }
filestore = { path = "../../filestore" }
manifest = { path = "../../manifest" }
mononoke_types = { path = "../../mononoke_types" }
repo_blobstore = { path = "../../blobrepo/repo_blobstore" }
cloned = { git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
failure_ext = { git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
futures_ext = { git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
anyhow = "1.0"
ascii = "1.0"
async-trait = "0.1.29"
bytes = { version = "0.5", features = ["serde"] }
digest = "0.8"
futures = { version = "0.3", features = ["async-await", "compat"] }
futures-old = { package = "futures", version = "0.1" }
itertools = "0.8"
sha-1 = "0.8"
sha2 = "0.8"
thiserror = "1.0"
tokio = { version = "=0.2.13", features = ["full"] }

[dev-dependencies]
blobrepo_factory = { path = "../../blobrepo/factory" }
blobrepo_hg = { path = "../../blobrepo/blobrepo_hg" }
bookmarks = { path = "../../bookmarks" }
fixtures = { path = "../../tests/fixtures" }
mercurial_types = { path = "../../mercurial/types" }
revset = { path = "../../revset" }
test_utils = { path = "../../manifest/test_utils" }
tests_utils = { path = "../../tests/utils" }
fbinit = { git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
maplit = "1.0"
tokio-compat = "0.1"
