[package]
name = "mononoke_repo"
edition = "2018"
version = "0.1.0"
authors = ['Facebook']
license = "GPLv2+"
include = ["src/**/*.rs"]

[dependencies]
blobrepo = { path = "../../blobrepo" }
blobrepo_factory = { path = "../../blobrepo/factory" }
context = { path = "../../server/context" }
getbundle_response = { path = "../getbundle_response" }
hooks = { path = "../../hooks" }
metaconfig_types = { path = "../../metaconfig/types" }
mononoke_types = { path = "../../mononoke_types" }
mutable_counters = { path = "../../mutable_counters" }
reachabilityindex = { path = "../../reachabilityindex" }
repo_blobstore = { path = "../../blobrepo/repo_blobstore" }
repo_read_write_status = { path = "../repo_read_write_status" }
reverse_filler_queue = { path = "../reverse_filler_queue" }
skiplist = { path = "../../reachabilityindex/skiplist" }
sql_construct = { path = "../../common/sql_construct" }
sql_ext = { path = "../../common/rust/sql_ext" }
streaming_clone = { path = "../streaming_clone" }
cloned = { git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
fbinit = { git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
futures_ext = { git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
anyhow = "1.0"
futures = { version = "0.3", features = ["async-await", "compat"] }
futures-old = { package = "futures", version = "0.1" }
rand = { version = "0.7", features = ["small_rng"] }
slog = { version = "2.5", features = ["max_level_debug"] }
tokio = { version = "=0.2.13", features = ["full"] }
