[package]
name = "mononoke_types-mocks"
edition = "2018"
version = "0.1.0"
authors = ['Facebook']
license = "GPLv2+"
include = ["**/*.rs"]

[lib]
path = "lib.rs"

[dependencies]
mononoke_types = { path = ".." }
chrono = { version="0.4", features=["serde"] }
lazy_static = "1.0"
