[package]
name = "pytreestate"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.20"
cpython_ext = { path = "../../../../lib/cpython-ext", default-features = false }
cpython = { version = "0.5", default-features = false }
parking_lot = "0.12.0"
treestate = { path = "../../../../lib/treestate" }

[features]
python2 = ["cpython/python27-sys", "cpython_ext/python2"]
python3 = ["cpython/python3-sys", "cpython_ext/python3"]
