[patch.crates-io]
abomonation = { git = "https://github.com/markbt/abomonation", rev = "0f43346d2afa2aedc64d61f3f4273e8d1e454642" }
aes-gcm-siv = { git = "https://github.com/lei2022/AEADs", rev = "d9d03399fbc1347a1c2941801c0743e847980757" }
curve25519-dalek = { git = "https://github.com/hariria/curve25519-dalek", rev = "1f39e7b369dc70f432370c9703229a45bfa9664e" }
graphql-parser = { git = "https://github.com/graphql-rust//graphql-parser", rev = "8d76425d83c40670570cc325f57c730262f07456" }
lru-disk-cache = { git = "https://github.com/mozilla/sccache", rev = "fdbf843d174c6796d736b2b61dab0297670390f8" }
mysql_async = { git = "https://github.com/mzr/mysql_async", rev = "76b6fa05d7bb3408402033e6f94042a756ab55ab" }
perf-event = { version = "0.4", git = "https://github.com/krallin/perf-event.git", rev = "86224a9bc025d5d19f719542f27c8c629a08b167" }
perf-event-open-sys = { version = "4.0", git = "https://github.com/krallin/perf-event.git", rev = "86224a9bc025d5d19f719542f27c8c629a08b167" }
quickcheck = { git = "https://github.com/jakoschiko/quickcheck", rev = "6ecdf5bb4b0132ce66670b4d46453aa022ea892c" }
solana-program = { git = "https://github.com/omertxyz/solana.git", rev = "03a3b241622b6248bb245c29baef538a88f04c0b" }
solana-zk-token-sdk = { git = "https://github.com/omertxyz/solana.git", rev = "03a3b241622b6248bb245c29baef538a88f04c0b" }
tar = { package = "tar", git = "https://github.com/jrwats/tar-rs.git", rev = "21eeccdc08d9b87f6ad610f9b20a5839aabe5974" }
terminfo = { git = "https://github.com/rust-terminfo/terminfo", rev = "9b4e1c6aae79644c9da7a2e312e3c10ee4759930" }
toml = { git = "https://github.com/fbsource/toml", rev = "0ee7001fb64f7c5094a00d3a360e402201f498fe" }
tonic = { version = "0.8.3", git = "https://github.com/krallin/tonic.git", rev = "c67fc25b636b48b90c83dfc8dd1f89c00b84846d" }
tonic-build = { version = "0.8.4", git = "https://github.com/krallin/tonic.git", rev = "c67fc25b636b48b90c83dfc8dd1f89c00b84846d" }
tracing = { git = "https://github.com/jsgf/tracing.git", rev = "f9fbbc6ae5d81ec59e4fd52ad3da1e261e8af681" }
tracing-appender = { git = "https://github.com/jsgf/tracing.git", rev = "f9fbbc6ae5d81ec59e4fd52ad3da1e261e8af681" }
tracing-core = { git = "https://github.com/jsgf/tracing.git", rev = "f9fbbc6ae5d81ec59e4fd52ad3da1e261e8af681" }
tracing-futures = { git = "https://github.com/jsgf/tracing.git", rev = "f9fbbc6ae5d81ec59e4fd52ad3da1e261e8af681" }
tracing-log = { git = "https://github.com/jsgf/tracing.git", rev = "f9fbbc6ae5d81ec59e4fd52ad3da1e261e8af681" }
tracing-serde = { git = "https://github.com/jsgf/tracing.git", rev = "f9fbbc6ae5d81ec59e4fd52ad3da1e261e8af681" }
tracing-subscriber = { git = "https://github.com/jsgf/tracing.git", rev = "f9fbbc6ae5d81ec59e4fd52ad3da1e261e8af681" }

[workspace]
members = [
  "benchmarks",
  "cli_rs/edenfs-client",
  "cli_rs/edenfs-commands",
  "cli_rs/edenfs-config",
  "cli_rs/edenfs-error",
  "cli_rs/edenfs-utils",
  "cli_rs/edenfsctl",
  "cli_rs/stack-config",
  "cli_rs/stack-config-derive",
  "config",
  "inodes/overlay",
  "service",
  "service/thrift_streaming",
]
