[patch.crates-io]
aes-gcm-siv = { git = "https://github.com/lei2022/AEADs", rev = "d9d03399fbc1347a1c2941801c0743e847980757" }
bindgen = { git = "https://github.com/fbsource/bindgen", rev = "9495ab5c085bebeb46be3dec10a70f7336b3b3cb" }
bindgen-cli = { git = "https://github.com/fbsource/bindgen", rev = "9495ab5c085bebeb46be3dec10a70f7336b3b3cb" }
bundlr-sdk = { git = "https://github.com/kaustavha/rust-sdk", rev = "4ed5b08398a9f9df284daf57888c314e4f7d4e1d" }
curve25519-dalek = { git = "https://github.com/hariria/curve25519-dalek", rev = "1f39e7b369dc70f432370c9703229a45bfa9664e" }
daemonize = { git = "https://github.com/krallin/daemonize", rev = "f7be28efa1b4a70e43bb37b5f4ff4d664992edca" }
deltae = { git = "https://github.com/markbt/deltae", rev = "1c6e9c7c9184751bd17795d78896d522e77a2ce4" }
graphql-parser = { git = "https://github.com/vmagro/graphql-parser", rev = "c778917f57f6b2c26d9291819b9bb341a2f5948a" }
lru-disk-cache = { git = "https://github.com/mozilla/sccache", rev = "fdbf843d174c6796d736b2b61dab0297670390f8" }
mysql_async = { git = "https://github.com/mzr/mysql_async", rev = "76b6fa05d7bb3408402033e6f94042a756ab55ab" }
quickcheck = { git = "https://github.com/jakoschiko/quickcheck", rev = "6ecdf5bb4b0132ce66670b4d46453aa022ea892c" }
reqwest = { git = "https://github.com/vmagro/reqwest", rev = "f9490c06756a9d35ab874c44657db790a87af80b" }
rustfilt = { git = "https://github.com/jsgf/rustfilt.git", rev = "8141fa7f1caee562ee8daffb2ddeca3d1f0d36e5" }
solana-program = { git = "https://github.com/omertxyz/solana.git", rev = "03a3b241622b6248bb245c29baef538a88f04c0b" }
solana-zk-token-sdk = { git = "https://github.com/omertxyz/solana.git", rev = "03a3b241622b6248bb245c29baef538a88f04c0b" }
tar = { package = "tar", git = "https://github.com/jrwats/tar-rs.git", rev = "21eeccdc08d9b87f6ad610f9b20a5839aabe5974" }
tempfile = { git = "https://github.com/Stebalien/tempfile.git", rev = "66aa57f7d3a38234fcd393077366b61d36171e42" }
terminfo = { git = "https://github.com/rust-terminfo/terminfo", rev = "9b4e1c6aae79644c9da7a2e312e3c10ee4759930" }
toml = { git = "https://github.com/fbsource/toml", branch = "dotted-table-0.5.8" }
windows-sys = { git = "https://github.com/fanzeyi/windows-rs", rev = "8775afca5d2017da427d34b291ae4f85f5820740" }
windows-sys028 = { package = "windows-sys", git = "https://github.com/wilfred/windows-rs", rev = "eacf60132fc798a8e59174a7f25471bad541a042" }

[workspace]
members = [
  "cli_rs/edenfs-client",
  "cli_rs/edenfs-commands",
  "cli_rs/edenfs-config",
  "cli_rs/edenfs-error",
  "cli_rs/edenfs-utils",
  "cli_rs/edenfsctl",
  "cli_rs/stack-config",
  "cli_rs/stack-config-derive",
  "config",
  "inodes/overlay",
  "service",
  "service/thrift_streaming",
]
