[patch.crates-io]
daemonize = { git = "https://github.com/krallin/daemonize", rev = "f7be28efa1b4a70e43bb37b5f4ff4d664992edca" }
lru-disk-cache = { git = "https://github.com/mozilla/sccache", rev = "033ebaae69beeb0ac04e8c35d6ff1103487bd9a3" }
mysql_async = { git = "https://github.com/mzr/mysql_async", rev = "76b6fa05d7bb3408402033e6f94042a756ab55ab" }
prost = { git = "https://github.com/gabrielrussoc/prost", branch = "protoc-runtime" }
prost-derive = { git = "https://github.com/gabrielrussoc/prost", branch = "protoc-runtime" }
prost-types = { git = "https://github.com/gabrielrussoc/prost", branch = "protoc-runtime" }
quickcheck = { git = "https://github.com/jakoschiko/quickcheck", rev = "6ecdf5bb4b0132ce66670b4d46453aa022ea892c" }
reqwest = { git = "https://github.com/vmagro/reqwest", rev = "ccd29cb852eefc24d7d3943c201e47b6b2e2599a" }
rustfilt = { git = "https://github.com/jsgf/rustfilt.git", rev = "8141fa7f1caee562ee8daffb2ddeca3d1f0d36e5" }
shellexpand = { git = "https://github.com/fanzeyi/shellexpand.git", rev = "179447a3f8fccd765acfd2eed15a54c716c49cfe" }
terminfo = { git = "https://github.com/rust-terminfo/terminfo", rev = "9b4e1c6aae79644c9da7a2e312e3c10ee4759930" }
toml = { git = "https://github.com/fbsource/toml", branch = "dotted-table-0.5.8" }

[workspace]
members = [
  "cli_rs/edenfs-client",
  "cli_rs/edenfs-commands",
  "cli_rs/edenfs-config",
  "cli_rs/edenfs-error",
  "cli_rs/edenfs-utils",
  "cli_rs/edenfsctl",
  "cli_rs/stack-config",
  "cli_rs/stack-config-derive",
  "config",
  "inodes/overlay",
  "service",
  "service/thrift_streaming",
]
