[patch.crates-io]
abomonation = { git = "https://github.com/markbt/abomonation", rev = "0f43346d2afa2aedc64d61f3f4273e8d1e454642" }
base64urlsafedata = { git = "https://github.com/kanidm/webauthn-rs.git", rev = "d278c56adfa39a0723c79bdcd461644194bc5138" }
bindgen = { git = "https://github.com/rust-lang/rust-bindgen", rev = "7e9043497297e04e91ae76dfe0d2e7998828e529" }
bindgen-cli = { git = "https://github.com/rust-lang/rust-bindgen", rev = "7e9043497297e04e91ae76dfe0d2e7998828e529" }
cxx = { package = "cxx", git = "https://github.com/facebookexperimental/cxx.git", rev = "cf9ae5500db7d31292d12a6b0728b0f6a1d7b9c9" }
cxx-build = { package = "cxx-build", git = "https://github.com/facebookexperimental/cxx.git", rev = "cf9ae5500db7d31292d12a6b0728b0f6a1d7b9c9" }
graphql-parser = { git = "https://github.com/graphql-rust//graphql-parser", rev = "8d76425d83c40670570cc325f57c730262f07456" }
lru-disk-cache = { git = "https://github.com/mozilla/sccache", rev = "fdbf843d174c6796d736b2b61dab0297670390f8" }
minijail = { git = "https://chromium.googlesource.com/chromiumos/platform/minijail", rev = "13be56d79718425a60173f61f8174669d9cc8930" }
perf-event = { version = "0.4", git = "https://github.com/krallin/perf-event.git", rev = "86224a9bc025d5d19f719542f27c8c629a08b167" }
perf-event-open-sys = { version = "4.0", git = "https://github.com/krallin/perf-event.git", rev = "86224a9bc025d5d19f719542f27c8c629a08b167" }
quickcheck = { git = "https://github.com/jakoschiko/quickcheck", rev = "6ecdf5bb4b0132ce66670b4d46453aa022ea892c" }
riscv = { git = "https://github.com/rust-embedded/riscv.git", rev = "e9f43ae4722cfcdda67d36fdfcf462a0f12e9928" }

[workspace]
members = [
  "benchmarks",
  "cli_rs/edenfs-client",
  "cli_rs/edenfs-commands",
  "cli_rs/edenfs-config",
  "cli_rs/edenfs-error",
  "cli_rs/edenfs-utils",
  "cli_rs/edenfsctl",
  "cli_rs/stack-config",
  "cli_rs/stack-config-derive",
  "config",
  "config/clients",
  "config/mocks",
  "config/services",
  "inodes/overlay",
  "inodes/overlay/clients",
  "inodes/overlay/mocks",
  "inodes/overlay/services",
  "service",
  "service/clients",
  "service/mocks",
  "service/services",
  "service/thrift_streaming",
  "service/thrift_streaming/clients",
  "service/thrift_streaming/mocks",
  "service/thrift_streaming/services",
]
resolver = "2"
