[package]
name = "globalrev_pushrebase_hook"
edition = "2018"
version = "0.1.0"
authors = ['Facebook']
license = "GPLv2+"
include = ["**/*.rs"]

[lib]
path = "lib.rs"

[dependencies]
bonsai_globalrev_mapping = { path = ".." }
bookmarks = { path = "../../bookmarks" }
context = { path = "../../server/context" }
mononoke_types = { path = "../../mononoke_types" }
pushrebase = { path = "../../pushrebase" }
sql = { git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
anyhow = "1.0"
async-trait = "0.1.29"
futures = { version = "0.3.5", features = ["async-await", "compat"] }

[dev-dependencies]
blobrepo_factory = { path = "../../blobrepo/factory" }
blobstore = { path = "../../blobstore" }
tests_utils = { path = "../../tests/utils" }
fbinit = { git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
maplit = "1.0"
rand = { version = "0.7", features = ["small_rng"] }
tokio = { version = "=0.2.13", features = ["full"] }
tokio-compat = "0.1"
