[package]
name = "eden_apfs_mount_helper"
version = "0.1.0"
authors = ["Wez Furlong"]
edition = "2021"
rust = "1.58.1"

[features]
default = ["json-plist"]
# native-plist = ["plist"]
json-plist = ["serde_json"]

[dependencies]
anyhow = "1.0"
# plist = {version="0.5",optional=true}
serde_json = {version="1.0",optional=true}
serde = {version="1.0", features=["derive"]}
sha2 = "0.8"
structopt = "0.3"
libc = "0.2"

[dev-dependencies]
pretty_assertions = "0.6"
