[package]
name = "blobimport_lib"
edition = "2018"
version = "0.1.0"
authors = ['Facebook']
license = "GPLv2+"
include = ["src/**/*.rs"]

[dependencies]
blobrepo = { path = "../blobrepo" }
bonsai_git_mapping = { path = "../bonsai_git_mapping" }
bonsai_globalrev_mapping = { path = "../bonsai_globalrev_mapping" }
bookmarks = { path = "../bookmarks" }
context = { path = "../server/context" }
derived_data_utils = { path = "../derived_data/utils" }
lfs_import_lib = { path = "../lfs_import_lib" }
mercurial_revlog = { path = "../mercurial/revlog" }
mercurial_types = { path = "../mercurial/types" }
mononoke_types = { path = "../mononoke_types" }
scuba_ext = { path = "../common/scuba_ext" }
synced_commit_mapping = { path = "../commit_rewriting/synced_commit_mapping" }
cloned = { git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
failure_ext = { git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
futures_ext = { git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
tracing = { git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
anyhow = "1.0"
ascii = "1.0"
bytes = { version = "0.5", features = ["serde"] }
futures = { version = "0.3", features = ["async-await", "compat"] }
futures-old = { package = "futures", version = "0.1" }
slog = { version = "2.5", features = ["max_level_debug"] }
tokio = "0.1"
