[package]
name = "mononoke_types"
edition = "2018"
version = "0.1.0"
authors = ['Facebook']
license = "GPLv2+"
include = ["src/**/*.rs"]

[dependencies]
blobstore = { path = "../blobstore" }
context = { path = "../server/context" }
mononoke_types-thrift = { path = "if" }
xdiff = { path = "../../scm/lib/xdiff" }
cloned = { git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
fbthrift = { git = "https://github.com/facebook/fbthrift.git", branch = "master" }
futures_ext = { git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
sql = { git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
abomonation = "0.7"
abomonation_derive = "0.5"
anyhow = "1.0"
ascii = "1.0"
bincode = "1.2"
blake2 = "0.8"
bytes = { version = "0.5", features = ["serde"] }
chrono = { version = "0.4", features = ["serde"] }
faster-hex = "0.4"
futures = { version = "0.3.5", features = ["async-await", "compat"] }
futures-old = { package = "futures", version = "0.1" }
itertools = "0.8"
lazy_static = "1.0"
quickcheck = "0.9"
rand = { version = "0.7", features = ["small_rng"] }
regex = "1.3.7"
serde = { version = "1.0", features = ["derive", "rc"] }
serde_derive = "1.0"
thiserror = "1.0"

[dev-dependencies]
fixtures = { path = "../tests/fixtures" }
fbinit = { git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
maplit = "1.0"
pretty_assertions = "0.6"
tokio-compat = "0.1"
