[patch.crates-io]
aes-gcm-siv = { git = "https://github.com/lei2022/AEADs", rev = "d9d03399fbc1347a1c2941801c0743e847980757" }
bundlr-sdk = { git = "https://github.com/kaustavha/rust-sdk", rev = "4ed5b08398a9f9df284daf57888c314e4f7d4e1d" }
curve25519-dalek = { git = "https://github.com/hariria/curve25519-dalek", rev = "1f39e7b369dc70f432370c9703229a45bfa9664e" }
daemonize = { git = "https://github.com/krallin/daemonize", rev = "f7be28efa1b4a70e43bb37b5f4ff4d664992edca" }
git-config = { git = "https://github.com/mzr/gitoxide", rev = "28c51a1d99af3f4e5ea8f6bb2319e0a5d812c891" }
graphql-parser = { git = "https://github.com/vmagro/graphql-parser", rev = "c778917f57f6b2c26d9291819b9bb341a2f5948a" }
lru-disk-cache = { git = "https://github.com/mozilla/sccache", rev = "fdbf843d174c6796d736b2b61dab0297670390f8" }
mysql_async = { git = "https://github.com/mzr/mysql_async", rev = "76b6fa05d7bb3408402033e6f94042a756ab55ab" }
quickcheck = { git = "https://github.com/jakoschiko/quickcheck", rev = "6ecdf5bb4b0132ce66670b4d46453aa022ea892c" }
reqwest = { git = "https://github.com/vmagro/reqwest", rev = "f9490c06756a9d35ab874c44657db790a87af80b" }
rustfilt = { git = "https://github.com/jsgf/rustfilt.git", rev = "8141fa7f1caee562ee8daffb2ddeca3d1f0d36e5" }
solana-program = { git = "https://github.com/omertxyz/solana.git", rev = "03a3b241622b6248bb245c29baef538a88f04c0b" }
solana-zk-token-sdk = { git = "https://github.com/omertxyz/solana.git", rev = "03a3b241622b6248bb245c29baef538a88f04c0b" }
tar = { package = "tar", git = "https://github.com/jrwats/tar-rs.git", rev = "21eeccdc08d9b87f6ad610f9b20a5839aabe5974" }
tempfile = { git = "https://github.com/Stebalien/tempfile.git", rev = "66aa57f7d3a38234fcd393077366b61d36171e42" }
terminfo = { git = "https://github.com/rust-terminfo/terminfo", rev = "9b4e1c6aae79644c9da7a2e312e3c10ee4759930" }
toml = { git = "https://github.com/fbsource/toml", branch = "dotted-table-0.5.8" }
windows-sys = { git = "https://github.com/fanzeyi/windows-rs", rev = "8775afca5d2017da427d34b291ae4f85f5820740" }
windows-sys028 = { package = "windows-sys", git = "https://github.com/wilfred/windows-rs", rev = "eacf60132fc798a8e59174a7f25471bad541a042" }

[workspace]
members = [
  "edenscmnative/conch_parser",
  "exec/eden_apfs_mount_helper",
  "exec/fsprobe",
  "exec/github-cli",
  "exec/hgmain",
  "exec/scm_daemon",
  "exec/scratch",
  "lib/async-runtime",
  "lib/atomicfile",
  "lib/auth",
  "lib/backingstore",
  "lib/blackbox",
  "lib/blackbox/serde_alt",
  "lib/cats",
  "lib/checkout",
  "lib/clidispatch",
  "lib/clientinfo",
  "lib/cliparser",
  "lib/clone",
  "lib/commitcloudsubscriber",
  "lib/config/model",
  "lib/config/parser",
  "lib/config/pest-hgrc",
  "lib/config/static",
  "lib/config/static/macros",
  "lib/config/union",
  "lib/cpython-async",
  "lib/cpython-ext",
  "lib/dag",
  "lib/dag/benches",
  "lib/dag/bindag",
  "lib/dag/dag-types",
  "lib/dag/gitdag",
  "lib/debugtop",
  "lib/dev-logger",
  "lib/doctor/network",
  "lib/drawdag",
  "lib/eagerepo",
  "lib/edenapi",
  "lib/edenapi/ext",
  "lib/edenapi/trait",
  "lib/edenapi/types",
  "lib/edenapi/types/proc_macros",
  "lib/edenfs-client",
  "lib/encoding",
  "lib/exchange",
  "lib/formatter",
  "lib/fsinfo",
  "lib/fsyncglob",
  "lib/github",
  "lib/gitstore",
  "lib/hg-http",
  "lib/hg-metrics",
  "lib/hgcommands",
  "lib/hgcommits",
  "lib/hgtime",
  "lib/http-client",
  "lib/identity",
  "lib/indexedlog",
  "lib/insta_ext",
  "lib/io",
  "lib/lazystr",
  "lib/lz4-pyframe",
  "lib/manifest",
  "lib/manifest-tree",
  "lib/metalog",
  "lib/metrics",
  "lib/metrics/render",
  "lib/migration",
  "lib/mincode",
  "lib/minibench",
  "lib/minibytes",
  "lib/mpatch",
  "lib/mpatch-sys",
  "lib/mutationstore",
  "lib/nodemap",
  "lib/nonblocking",
  "lib/pathhistory",
  "lib/pathmatcher",
  "lib/pprint",
  "lib/procinfo",
  "lib/progress/model",
  "lib/progress/render",
  "lib/radixbuf",
  "lib/refencode",
  "lib/renderdag",
  "lib/repo",
  "lib/repo_name",
  "lib/repolock",
  "lib/revisionstore",
  "lib/revisionstore/types",
  "lib/revlogindex",
  "lib/runlog",
  "lib/sparse",
  "lib/spawn-ext",
  "lib/status",
  "lib/storemodel",
  "lib/streams",
  "lib/termlogger",
  "lib/third-party/conch-parser",
  "lib/thrift-types",
  "lib/tracing-analyzer",
  "lib/tracing-collector",
  "lib/tracing-reload",
  "lib/tracing-runtime-callsite",
  "lib/tracing-sampler",
  "lib/treestate",
  "lib/types",
  "lib/util",
  "lib/version",
  "lib/vfs",
  "lib/vlqencoding",
  "lib/workingcopy",
  "lib/xdiff",
  "lib/xdiff-sys",
  "lib/zstdelta",
  "lib/zstore",
]
