[patch.crates-io]
deltae = { git = "https://github.com/markbt/deltae", rev = "1c6e9c7c9184751bd17795d78896d522e77a2ce4" }
reqwest = { git = "https://github.com/vmagro/reqwest", rev = "f9490c06756a9d35ab874c44657db790a87af80b" }

[workspace]
members = [
  "edenscmnative/conch_parser",
  "exec/eden_apfs_mount_helper",
  "exec/fsprobe",
  "exec/hgmain",
  "exec/scm_daemon",
  "exec/scratch",
  "lib/async-runtime",
  "lib/atomicfile",
  "lib/auth",
  "lib/backingstore",
  "lib/blackbox",
  "lib/blackbox/serde_alt",
  "lib/cats",
  "lib/checkout",
  "lib/clidispatch",
  "lib/clientinfo",
  "lib/cliparser",
  "lib/clone",
  "lib/commitcloudsubscriber",
  "lib/config/hgrc-parser",
  "lib/config/loader",
  "lib/config/model",
  "lib/config/set",
  "lib/config/static",
  "lib/config/static/macros",
  "lib/config/union",
  "lib/control-point",
  "lib/cpython-async",
  "lib/cpython-ext",
  "lib/dag",
  "lib/dag/benches",
  "lib/dag/bindag",
  "lib/dag/dag-types",
  "lib/dag/gitdag",
  "lib/debugtop",
  "lib/dev-logger",
  "lib/doctor/network",
  "lib/drawdag",
  "lib/eagerepo",
  "lib/edenapi",
  "lib/edenapi/ext",
  "lib/edenapi/trait",
  "lib/edenapi/types",
  "lib/edenapi/types/proc_macros",
  "lib/edenfs-client",
  "lib/encoding",
  "lib/exchange",
  "lib/formatter",
  "lib/fsinfo",
  "lib/fsyncglob",
  "lib/gitstore",
  "lib/hg-http",
  "lib/hg-metrics",
  "lib/hgcommands",
  "lib/hgcommits",
  "lib/hgtime",
  "lib/http-client",
  "lib/identity",
  "lib/indexedlog",
  "lib/insta_ext",
  "lib/io",
  "lib/io/term/logger",
  "lib/io/term/style",
  "lib/lazystr",
  "lib/lz4-pyframe",
  "lib/manifest",
  "lib/manifest-tree",
  "lib/metalog",
  "lib/metrics",
  "lib/metrics/render",
  "lib/migration",
  "lib/mincode",
  "lib/minibench",
  "lib/minibytes",
  "lib/mpatch",
  "lib/mpatch-sys",
  "lib/mutationstore",
  "lib/nodemap",
  "lib/nonblocking",
  "lib/pathhistory",
  "lib/pathmatcher",
  "lib/pprint",
  "lib/procinfo",
  "lib/progress/model",
  "lib/progress/render",
  "lib/radixbuf",
  "lib/refencode",
  "lib/renderdag",
  "lib/repo",
  "lib/repo_name",
  "lib/repolock",
  "lib/revisionstore",
  "lib/revisionstore/types",
  "lib/revlogindex",
  "lib/revsets",
  "lib/runlog",
  "lib/sparse",
  "lib/spawn-ext",
  "lib/status",
  "lib/storemodel",
  "lib/streams",
  "lib/third-party/conch-parser",
  "lib/thrift-types",
  "lib/tracing-analyzer",
  "lib/tracing-collector",
  "lib/tracing-reload",
  "lib/tracing-runtime-callsite",
  "lib/tracing-sampler",
  "lib/treestate",
  "lib/types",
  "lib/util",
  "lib/util/hgplain",
  "lib/version",
  "lib/vfs",
  "lib/vlqencoding",
  "lib/workingcopy",
  "lib/xdiff",
  "lib/xdiff-sys",
  "lib/zstdelta",
  "lib/zstore",
]
