[package]
name = "pypathmatcher"
version = "0.1.0"
edition = "2018"

[dependencies]
cpython-ext = { path = "../../../../lib/cpython-ext" }
cpython = { version = "0.3", features = ["python27-sys"], default-features = false }
encoding = { path = "../../../../lib/encoding" }
pathmatcher = { path = "../../../../lib/pathmatcher" }
types = { path = "../../../../lib/types" }
