[package]
name = "pydag"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = "1.0.20"
cpython-ext = { path = "../../../../lib/cpython-ext", default-features = false }
cpython = { version = "0.5", default-features = false }
dag = { path = "../../../../lib/dag" }
renderdag = { path = "../../../../lib/renderdag" }

[features]
python2 = ["cpython/python27-sys", "cpython-ext/python2"]
python3 = ["cpython/python3-sys", "cpython-ext/python3"]
