[package]
name = "pystackdesc"
version = "0.1.0"
edition = "2018"

[dependencies]
cpython = { version = "0.3", features = ["python27-sys"], default-features = false }
stackdesc = { path = "../../../../lib/stackdesc/" }
