[package]
name = "pyzstd"
version = "0.1.0"
edition = "2021"

[dependencies]
cpython_ext = { path = "../../../../lib/cpython-ext" }
cpython = { version = "0.7", default-features = false }
zstd = "0.11.1+zstd.1.5.2"
zstd-safe = "5.0.1+zstd.1.5.2"
zstdelta = { path = "../../../../lib/zstdelta/" }
