[package]
name = "getbundle_response"
edition = "2018"
version = "0.1.0"
authors = ['Facebook']
license = "GPLv2+"
include = ["src/**/*.rs"]

[dependencies]
blobrepo = { path = "../../blobrepo" }
blobrepo_hg = { path = "../../blobrepo/blobrepo_hg" }
blobstore = { path = "../../blobstore" }
context = { path = "../../server/context" }
derived_data = { path = "../../derived_data" }
derived_data_filenodes = { path = "../../derived_data/filenodes" }
filestore = { path = "../../filestore" }
load_limiter = { path = "../../load_limiter" }
manifest = { path = "../../manifest" }
mercurial_bundles = { path = "../../mercurial/bundles" }
mercurial_revlog = { path = "../../mercurial/revlog" }
mercurial_types = { path = "../../mercurial/types" }
mononoke_types = { path = "../../mononoke_types" }
phases = { path = "../../phases" }
reachabilityindex = { path = "../../reachabilityindex" }
repo_blobstore = { path = "../../blobrepo/repo_blobstore" }
revset = { path = "../../revset" }
tunables = { path = "../../tunables" }
cloned = { git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
futures_ext = { git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
stats = { git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
anyhow = "1.0"
bytes = { version = "0.5", features = ["serde"] }
bytes-old = { package = "bytes", version = "0.4", features = ["serde"] }
futures = { version = "0.3.5", features = ["async-await", "compat"] }
futures-old = { package = "futures", version = "0.1" }
futures-util = "0.3"
slog = { version = "2.5", features = ["max_level_debug"] }
thiserror = "1.0"
