[package]
name = "pytreestate"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.20"
cpython_ext = { path = "../../../../lib/cpython-ext" }
cpython = { version = "0.7", default-features = false }
parking_lot = "0.11.2"
pathmatcher = { path = "../../../../lib/pathmatcher" }
pypathmatcher = { path = "../pypathmatcher" }
treestate = { path = "../../../../lib/treestate" }
types = { path = "../../../../lib/types" }
vfs = { path = "../../../../lib/vfs" }

