[package]
name = "pyprocess"
version = "0.1.0"
edition = "2018"

[dependencies]
cpython = { version = "0.5", default-features = false }
cpython_ext = { path = "../../../../lib/cpython-ext", default-features = false }
spawn-ext = { path = "../../../../lib/spawn-ext" }

[features]
python2 = ["cpython/python27-sys", "cpython_ext/python2"]
python3 = ["cpython/python3-sys", "cpython_ext/python3"]
