[package]
name = "async-compression"
version = "0.0.1"
authors = ["Facebook"]
license = "GPLv2+"
edition = "2018"

[dependencies]
bytes = "0.4.8"
bzip2 = "0.3.2"
flate2 = "1.0.1"
futures = "0.1.17"
tokio-io = "0.1.4"
zstd = "0.4.18"
