[package]
name = "pytracing"
version = "0.1.0"
edition = "2021"

[dependencies]
cpython_ext = { path = "../../../../lib/cpython-ext" }
cpython = { version = "0.7", default-features = false }
lazy_static = "1"
mincode = { path = "../../../../lib/mincode" }
parking_lot = "0.11.2"
python3-sys = { version = "0.7" }
serde_json = "1"
tracing = "0.1"
tracing-collector = { path = "../../../../lib/tracing-collector" }
tracing-reload = { path = "../../../../lib/tracing-reload" }
tracing-runtime-callsite = { path = "../../../../lib/tracing-runtime-callsite" }
