[package]
name = "pyhgmetrics"
version = "0.1.0"
edition = "2021"


[dependencies]
cpython = { version = "0.7", default-features = false }
cpython_ext = { path = "../../../../lib/cpython-ext" }
hg-metrics = { path = "../../../../lib/hg-metrics" }
