[package]
name = "repo_read_write_status"
edition = "2018"
version = "0.1.0"
authors = ['Facebook']
license = "GPLv2+"
include = ["../schemas/**/*.sql", "src/**/*.rs"]

[dependencies]
metaconfig_types = { path = "../../metaconfig/types" }
sql_construct = { path = "../../common/sql_construct" }
sql_ext = { path = "../../common/rust/sql_ext" }
futures_ext = { git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
sql = { git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
anyhow = "1.0"
futures-old = { package = "futures", version = "0.1" }

[dev-dependencies]
async_unit = { git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
futures = { version = "0.3.5", features = ["async-await", "compat"] }
