[package]
name = "mkscratch"
version = "0.1.0"
authors = ["Source Control Oncall oncall+source_control@xmail.facebook.com"]
edition = "2018"

[dependencies]
anyhow = "1.0.20"
clap = "2.31.2"
dirs = "1.0"
libc = "0.2" # version taken from fbcode/third-party2/.../crates.io/..
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
