[package]
name = "megarepolib"
version = "0.1.0"
authors = ["Facebook"]
edition = "2018"
license = "GPLv2+"

[[bin]]
name = "megarepotool"
path = "tool/main.rs"

[dependencies]
anyhow = "1.0"
ascii = "1.0"
blobrepo = { version = "0.1.0", path = "../../blobrepo" }
blobrepo_hg = { version = "0.1.0", path = "../../blobrepo/blobrepo_hg" }
blobrepo_utils = { version = "0.1.0", path = "../../blobrepo_utils" }
blobstore = { version = "0.1.0", path = "../../blobstore" }
bookmarks = { version = "0.1.0", path = "../../bookmarks" }
borrowed = { version = "0.1.0", git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
cacheblob = { version = "0.1.0", path = "../../blobstore/cacheblob" }
cached_config = { version = "0.1.0", git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
clap = "2.33"
cloned = { version = "0.1.0", git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
cmdlib = { version = "0.1.0", path = "../../cmdlib" }
cmdlib_x_repo = { version = "0.1.0", path = "../../cmdlib/x_repo" }
commit_transformation = { version = "0.1.0", path = "../../megarepo_api/commit_transformation" }
context = { version = "0.1.0", path = "../../server/context" }
cross_repo_sync = { version = "0.1.0", path = "../cross_repo_sync" }
derived_data = { version = "0.1.0", path = "../../derived_data" }
fbinit = { version = "0.1.0", git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
futures = { version = "0.3.13", features = ["async-await", "compat"] }
futures-old = { package = "futures", version = "0.1.31" }
futures_ext = { package = "futures_01_ext", version = "0.1.0", git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
itertools = "0.10.1"
live_commit_sync_config = { version = "0.1.0", path = "../live_commit_sync_config" }
manifest = { version = "0.1.0", path = "../../manifest" }
maplit = "1.0"
mercurial_types = { version = "0.1.0", path = "../../mercurial/types" }
metaconfig_types = { version = "0.1.0", path = "../../metaconfig/types" }
mononoke_api_types = { version = "0.1.0", path = "../../mononoke_api/types" }
mononoke_types = { version = "0.1.0", path = "../../mononoke_types" }
movers = { version = "0.1.0", path = "../movers" }
pushrebase = { version = "0.1.0", path = "../../pushrebase" }
reachabilityindex = { version = "0.1.0", path = "../../reachabilityindex" }
regex = "1.4.2"
revset = { version = "0.1.0", path = "../../revset" }
slog = { version = "2.5", features = ["max_level_trace"] }
sorted_vector_map = { version = "0.1.0", git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
sql_ext = { version = "0.1.0", path = "../../common/rust/sql_ext" }
synced_commit_mapping = { version = "0.1.0", path = "../synced_commit_mapping" }
tokio = { version = "1.7.1", features = ["full", "test-util"] }
tokio-stream = { version = "0.1.4", features = ["fs", "io-util", "net", "signal", "sync", "time"] }
unodes = { version = "0.1.0", path = "../../derived_data/unodes" }

[dev-dependencies]
cross_repo_sync_test_utils = { version = "0.1.0", path = "../cross_repo_sync/test_utils" }
fbinit-tokio = { version = "0.1.0", git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
fixtures = { version = "0.1.0", path = "../../tests/fixtures" }
test_repo_factory = { version = "0.1.0", path = "../../repo_factory/test_repo_factory" }
tests_utils = { version = "0.1.0", path = "../../tests/utils" }

[patch.crates-io]
addr2line = { git = "https://github.com/gimli-rs/addr2line.git", rev = "0b6b6018b5b252a18e628fba03885f7d21844b3c" }
chashmap = { git = "https://gitlab.redox-os.org/ahornby/chashmap", rev = "901ace2ca3cdbc2095adb1af111d211e254e2aae" }
const-random = { git = "https://github.com/fbsource/const-random", rev = "374c5b46427fe2ffbf6acbd9c1687e0f1a809f95" }
curl = { git = "https://github.com/kulshrax/curl-rust", rev = "2a15bbd8dbbd54734313fa703a64db7ce6ddaff0" }
curl-sys = { git = "https://github.com/kulshrax/curl-rust", rev = "2a15bbd8dbbd54734313fa703a64db7ce6ddaff0" }
enumset = { git = "https://github.com/danobi/enumset", rev = "4c01c583c27a725948fededbfb3461c572a669a4" }
lru-disk-cache = { git = "https://github.com/mozilla/sccache", rev = "033ebaae69beeb0ac04e8c35d6ff1103487bd9a3" }
mysql_common = { git = "https://github.com/iammxt/rust_mysql_common", rev = "0e4c86952f1e799960e736c0b2bb9d2a6d935bf1" }
object = { git = "https://github.com/andrewjcg/object", rev = "ddbae7208292a13a016e8952c256f69737c763ab" }
openssl = { git = "https://github.com/sfackler/rust-openssl", rev = "68fc8ba890d77986b06ca5ce29d1089285fbbcf9" }
openssl-sys = { git = "https://github.com/sfackler/rust-openssl", rev = "68fc8ba890d77986b06ca5ce29d1089285fbbcf9" }
petgraph = { git = "https://github.com/jkeljo/petgraph", rev = "e3e9dd8632d23973fdc0b42c1117d5e5fc5fa384" }
prost = { git = "https://github.com/gabrielrussoc/prost", branch = "protoc-runtime" }
prost-derive = { git = "https://github.com/gabrielrussoc/prost", branch = "protoc-runtime" }
prost-types = { git = "https://github.com/gabrielrussoc/prost", branch = "protoc-runtime" }
r2d2_sqlite = { git = "https://github.com/jsgf/r2d2-sqlite.git", rev = "6d77a828ca0a3c507a3f58561532a1b6c66c7918" }
rustfilt = { git = "https://github.com/jsgf/rustfilt.git", rev = "8141fa7f1caee562ee8daffb2ddeca3d1f0d36e5" }
tokio-core = { git = "https://github.com/bolinfest/tokio-core", rev = "5f37aa3c627d56ee49154bc851d6930f5ab4398f" }
toml = { git = "https://github.com/jsgf/toml-rs", branch = "dotted-table-0.5.7" }
