[package]
name = "hooks"
edition = "2018"
version = "0.1.0"
authors = ['Facebook']
license = "GPLv2+"
include = ["src/**/*.rs"]

[lib]
test = false
doctest = false

[dependencies]
bookmarks = { path = "../bookmarks" }
context = { path = "../server/context" }
hooks_content_stores = { path = "content-stores" }
mercurial_types = { path = "../mercurial/types" }
metaconfig_types = { path = "../metaconfig/types" }
mononoke_types = { path = "../mononoke_types" }
permission_checker = { path = "../permission_checker" }
scuba_ext = { path = "../common/scuba_ext" }
cloned = { git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
fbinit = { git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
futures_stats = { git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
scuba = { git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
stats = { git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
anyhow = "1.0"
async-trait = "0.1.29"
bytes = { version = "0.5", features = ["serde"] }
futures = { version = "0.3", features = ["async-await", "compat"] }
hyper = "0.13"
hyper-tls = "0.4"
ipnetwork = "0.15"
itertools = "0.8"
lazy_static = "1.0"
maplit = "1.0"
regex = "1.3.7"
serde = { version = "1.0", features = ["derive", "rc"] }
serde_derive = "1.0"
serde_json = "1.0"
slog = { version = "2.5", features = ["max_level_debug"] }
tempdir = "0.3"
thiserror = "1.0"
tokio = { version = "=0.2.13", features = ["full"] }
