[package]
name = "hooks"
version = "0.1.0"
authors = ["Facebook"]
edition = "2018"
license = "GPLv2+"

[lib]
test = false
doctest = false

[[test]]
name = "hooks_tests"
path = "hooks-tests/src/lib.rs"

[dependencies]
anyhow = "1.0"
async-trait = "0.1.51"
bookmarks = { version = "0.1.0", path = "../bookmarks" }
bytes = { version = "1.0", features = ["serde"] }
cloned = { version = "0.1.0", git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
context = { version = "0.1.0", path = "../server/context" }
fbinit = { version = "0.1.0", git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
futures = { version = "0.3.13", features = ["async-await", "compat"] }
futures_stats = { version = "0.1.0", git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
hooks_content_stores = { version = "0.1.0", path = "content-stores" }
hyper = { version = "0.14.7", features = ["client", "http1", "http2"] }
hyper-tls = "0.5"
ipnetwork = "0.15"
itertools = "0.10.1"
lazy_static = "1.0"
manifest = { version = "0.1.0", path = "../manifest" }
maplit = "1.0"
mercurial_types = { version = "0.1.0", path = "../mercurial/types" }
metaconfig_types = { version = "0.1.0", path = "../metaconfig/types" }
mononoke_types = { version = "0.1.0", path = "../mononoke_types" }
permission_checker = { version = "0.1.0", path = "../permission_checker" }
regex = "1.4.2"
scuba = { version = "0.1.0", git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
scuba_ext = { version = "0.1.0", path = "../common/scuba_ext" }
serde = { version = "1.0.126", features = ["derive", "rc"] }
serde_derive = "1.0"
serde_json = { version = "1.0", features = ["float_roundtrip"] }
slog = { version = "2.5", features = ["max_level_trace"] }
stats = { version = "0.1.0", git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
tempdir = "0.3"
thiserror = "1.0"
tokio = { version = "1.7.1", features = ["full", "test-util"] }

[dev-dependencies]
blobrepo = { version = "0.1.0", path = "../blobrepo" }
blobstore = { version = "0.1.0", path = "../blobstore" }
borrowed = { version = "0.1.0", git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
fbinit-tokio = { version = "0.1.0", git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
fixtures = { version = "0.1.0", path = "../tests/fixtures" }
mononoke_types-mocks = { version = "0.1.0", path = "../mononoke_types/mocks" }
sorted_vector_map = { version = "0.1.0", git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
test_repo_factory = { version = "0.1.0", path = "../repo_factory/test_repo_factory" }
tests_utils = { version = "0.1.0", path = "../tests/utils" }

[patch.crates-io]
lru-disk-cache = { git = "https://github.com/mozilla/sccache", rev = "033ebaae69beeb0ac04e8c35d6ff1103487bd9a3" }
mysql_common = { git = "https://github.com/iammxt/rust_mysql_common", rev = "0e4c86952f1e799960e736c0b2bb9d2a6d935bf1" }
object = { git = "https://github.com/andrewjcg/object", rev = "ddbae7208292a13a016e8952c256f69737c763ab" }
prost = { git = "https://github.com/gabrielrussoc/prost", branch = "protoc-runtime" }
prost-derive = { git = "https://github.com/gabrielrussoc/prost", branch = "protoc-runtime" }
prost-types = { git = "https://github.com/gabrielrussoc/prost", branch = "protoc-runtime" }
rustfilt = { git = "https://github.com/jsgf/rustfilt.git", rev = "8141fa7f1caee562ee8daffb2ddeca3d1f0d36e5" }
tokio-core = { git = "https://github.com/bolinfest/tokio-core", rev = "5f37aa3c627d56ee49154bc851d6930f5ab4398f" }
toml = { git = "https://github.com/jsgf/toml-rs", branch = "dotted-table-0.5.7" }
