[package]
name = "pyrevlogindex"
version = "0.1.0"
edition = "2018"

[dependencies]
cpython = { version = "0.5", default-features = false }
cpython_ext = { path = "../../../../lib/cpython-ext", default-features = false }
dag = { path = "../../../../lib/dag" }
pybytes = { path = "../pybytes" }
pydag = { path = "../pydag" }
revlogindex = { path = "../../../../lib/revlogindex" }

[features]
python2 = ["cpython/python27-sys", "cpython_ext/python2", "pybytes/python2"]
python3 = ["cpython/python3-sys", "cpython_ext/python3", "pybytes/python2"]
