[package]
name = "pymanifest"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = "1.0.20"
bytes = { version = "0.5" }
cpython-ext = { path = "../../../../lib/cpython-ext", default-features = false }
cpython = { version = "0.4", default-features = false }
manifest = { path = "../../../../lib/manifest" }
manifest-tree = { path = "../../../../lib/manifest-tree" }
pathmatcher = { path = "../../../../lib/pathmatcher" }
pypathmatcher = { path = "../pypathmatcher" }
pyrevisionstore = { path = "../pyrevisionstore" }
revisionstore = { path = "../../../../lib/revisionstore" }
types = { path = "../../../../lib/types" }
