[package]
name = "hgproto"
version = "0.0.1"
authors = ["Facebook"]
license = "GPLv2+"
edition = "2018"

[dependencies]
bytes = "0.4.5"
error-chain = "0.11.0"
futures = "0.1.17"
nom = "3.2.1"
slog = "2.0.12"
tokio-io = "0.1.4"
tokio-proto = "0.1.1"

futures-ext = { path = "../futures-ext" }
