[package]
name = "pycheckout"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.20"
async-runtime = { path = "../../../../lib/async-runtime" }
checkout = { path = "../../../../lib/checkout" }
cpython_ext = { path = "../../../../lib/cpython-ext", default-features = false }
cpython = { version = "0.7", default-features = false }
manifest-tree = { path = "../../../../lib/manifest-tree" }
pathmatcher = { path = "../../../../lib/pathmatcher" }
pyconfigparser = { path = "../pyconfigparser" }
pypathmatcher = { path = "../pypathmatcher" }
pymanifest = { path = "../pymanifest" }
pyrevisionstore = { path = "../pyrevisionstore" }
pystatus = { path = "../pystatus" }
pytreestate = { path = "../pytreestate" }
revisionstore = { path = "../../../../lib/revisionstore" }
vfs = { path = "../../../../lib/vfs" }
tracing = "0.1"
treestate = { path = "../../../../lib/treestate" }
types = { path = "../../../../lib/types" }
