[package]
name = "walker"
version = "0.1.0"
authors = ["Facebook"]
edition = "2018"
license = "GPLv2+"

[dependencies]
ahash = "0.4.4"
anyhow = "1.0"
array-init = "0.1"
async-trait = "0.1.45"
async_compression = { version = "0.1.0", git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
auto_impl = "0.4"
bitflags = "1.2"
blame = { version = "0.1.0", path = "../derived_data/blame" }
blobrepo = { version = "0.1.0", path = "../blobrepo" }
blobrepo_hg = { version = "0.1.0", path = "../blobrepo/blobrepo_hg" }
blobstore = { version = "0.1.0", path = "../blobstore" }
blobstore_factory = { version = "0.1.0", path = "../blobstore/factory" }
bonsai_hg_mapping = { version = "0.1.0", path = "../bonsai_hg_mapping" }
bookmarks = { version = "0.1.0", path = "../bookmarks" }
bounded_traversal = { version = "0.1.0", path = "../common/bounded_traversal" }
bulkops = { version = "0.1.0", path = "../bulkops" }
bytes = { version = "0.5", features = ["serde"] }
changeset_info = { version = "0.1.0", path = "../derived_data/changeset_info" }
clap = "2.33"
cloned = { version = "0.1.0", git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
cmdlib = { version = "0.1.0", path = "../cmdlib" }
context = { version = "0.1.0", path = "../server/context" }
dashmap = { version = "4.0.2", features = ["serde"] }
deleted_files_manifest = { version = "0.1.0", path = "../derived_data/deleted_files_manifest" }
derive_more = "0.99.3"
derived_data = { version = "0.1.0", path = "../derived_data" }
derived_data_filenodes = { version = "0.1.0", path = "../derived_data/filenodes" }
fastlog = { version = "0.1.0", path = "../derived_data/fastlog" }
fbinit = { version = "0.1.0", git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
filenodes = { version = "0.1.0", path = "../filenodes" }
filestore = { version = "0.1.0", path = "../filestore" }
filetime = "0.2.9"
fsnodes = { version = "0.1.0", path = "../derived_data/fsnodes" }
futures = { version = "0.3.13", features = ["async-await", "compat"] }
hash_memo = { version = "0.1.0", git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
hex = "0.4"
internment = { version = "0.4.2", features = ["serde"] }
itertools = "0.8"
manifest = { version = "0.1.0", path = "../manifest" }
maplit = "1.0"
mercurial_derived_data = { version = "0.1.0", path = "../derived_data/mercurial_derived_data" }
mercurial_types = { version = "0.1.0", path = "../mercurial/types" }
metaconfig_types = { version = "0.1.0", path = "../metaconfig/types" }
mononoke_types = { version = "0.1.0", path = "../mononoke_types" }
multiplexedblob = { version = "0.1.0", path = "../blobstore/multiplexedblob" }
newfilenodes = { version = "0.1.0", path = "../newfilenodes" }
once_cell = "1.4"
paste = "1.0"
percent-encoding = "2.1"
phases = { version = "0.1.0", path = "../phases" }
regex = "1.4.2"
repo_factory = { version = "0.1.0", path = "../repo_factory" }
samplingblob = { version = "0.1.0", path = "../blobstore/samplingblob" }
scuba = { version = "0.1.0", git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
scuba_ext = { version = "0.1.0", path = "../common/scuba_ext" }
skeleton_manifest = { version = "0.1.0", path = "../derived_data/skeleton_manifest" }
slog = { version = "2.5", features = ["max_level_debug"] }
sql = { version = "0.1.0", git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
sql_construct = { version = "0.1.0", path = "../common/sql_construct" }
sql_ext = { version = "0.1.0", path = "../common/rust/sql_ext" }
stats = { version = "0.1.0", git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
strum = "0.19"
strum_macros = "0.19"
thiserror = "1.0"
tokio = { version = "0.2.25", features = ["full", "test-util"] }
unodes = { version = "0.1.0", path = "../derived_data/unodes" }

[dev-dependencies]
fbinit-tokio-02 = { version = "0.1.0", git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
test_repo_factory = { version = "0.1.0", path = "../repo_factory/test_repo_factory" }
