[package]
name = "gitimport"
edition = "2018"
version = "0.1.0"
authors = ['Facebook']
license = "GPLv2+"
include = ["src/**/*.rs"]

[dependencies]
blobrepo_override = { path = "../../blobrepo/override" }
blobstore = { path = "../../blobstore" }
bonsai_hg_mapping = { path = "../../bonsai_hg_mapping" }
cacheblob = { path = "../../blobstore/cacheblob" }
changesets = { path = "../../changesets" }
cmdlib = { path = "../../cmdlib" }
context = { path = "../../server/context" }
import_tools = { path = "../import_tools" }
mercurial_types = { path = "../../mercurial/types" }
mononoke_types = { path = "../../mononoke_types" }
fbinit = { git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
futures_ext = { git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
lock_ext = { git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
anyhow = "1.0"
clap = "2.33"
futures = { version = "0.3", features = ["async-await", "compat"] }
futures-old = { package = "futures", version = "0.1" }
git2 = "0.13"
linked-hash-map = { version = "0.5", features = ["serde_impl"] }
