[package]
name = "repo_listener"
version = "0.1.0"
authors = ["Facebook"]
edition = "2018"
license = "GPLv2+"

[dependencies]
alpn = { version = "0.1.0", path = "../../alpn" }
anyhow = "1.0"
backsyncer = { version = "0.1.0", path = "../../commit_rewriting/backsyncer" }
base64 = "0.11.0"
blobrepo = { version = "0.1.0", path = "../../blobrepo" }
blobstore_factory = { version = "0.1.0", path = "../../blobstore/factory" }
borrowed = { version = "0.1.0", git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
bytes = { version = "0.5", features = ["serde"] }
bytes-old = { package = "bytes", version = "0.4", features = ["serde"] }
bytes_ext = { version = "0.1.0", git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
cache_warmup = { version = "0.1.0", path = "../../cache_warmup" }
cached_config = { version = "0.1.0", git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
cloned = { version = "0.1.0", git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
cmdlib = { version = "0.1.0", path = "../../cmdlib" }
context = { version = "0.1.0", path = "../context" }
edenapi_service = { version = "0.1.0", path = "../../edenapi_service" }
failure_ext = { version = "0.1.0", git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
fbinit = { version = "0.1.0", git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
futures = { version = "0.3.13", features = ["async-await", "compat"] }
futures-old = { package = "futures", version = "0.1.31" }
futures-util = "0.3.7"
futures_01_ext = { version = "0.1.0", git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
futures_ext = { version = "0.1.0", git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
futures_stats = { version = "0.1.0", git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
gotham_ext = { version = "0.1.0", path = "../../gotham_ext" }
hgproto = { version = "0.1.0", path = "../../hgproto" }
hostname = { version = "0.1.0", git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
http = "0.2"
hyper = "0.13.10"
lazy_static = "1.0"
load_limiter = { version = "0.1.0", path = "../../load_limiter" }
maplit = "1.0"
metaconfig_types = { version = "0.1.0", path = "../../metaconfig/types" }
mononoke_api = { version = "0.1.0", path = "../../mononoke_api" }
mononoke_types = { version = "0.1.0", path = "../../mononoke_types" }
openssl = "0.10"
percent-encoding = "2.1"
permission_checker = { version = "0.1.0", path = "../../permission_checker" }
qps = { version = "0.1.0", path = "../qps" }
quiet_stream = { version = "0.1.0", path = "../../quiet_stream" }
repo_client = { version = "0.1.0", path = "../../repo_client" }
scribe_ext = { version = "0.1.0", path = "../../common/scribe_ext" }
scuba_ext = { version = "0.1.0", path = "../../common/scuba_ext" }
session_id = { version = "0.1.0", path = "../session_id" }
sha-1 = "0.8"
slog = { version = "2.5", features = ["max_level_debug"] }
slog-kvfilter = "0.7"
slog-term = "2.4.2"
slog_ext = { version = "0.1.0", path = "../../common/rust/slog_ext" }
sql_construct = { version = "0.1.0", path = "../../common/sql_construct" }
sql_ext = { version = "0.1.0", path = "../../common/rust/sql_ext" }
sshrelay = { version = "0.1.0", path = "../../sshrelay" }
stats = { version = "0.1.0", git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
synced_commit_mapping = { version = "0.1.0", path = "../../commit_rewriting/synced_commit_mapping" }
thiserror = "1.0"
time_ext = { version = "0.1.0", git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
tokio = { version = "0.2.25", features = ["full", "test-util"] }
tokio-openssl = "0.4"
tokio-util = { version = "0.3", features = ["codec", "udp"] }
tunables = { version = "0.1.0", path = "../../tunables" }

[patch.crates-io]
addr2line = { git = "https://github.com/gimli-rs/addr2line.git", rev = "0b6b6018b5b252a18e628fba03885f7d21844b3c" }
bytecount = { git = "https://github.com/llogiq/bytecount", rev = "469eaf8395c99397cd64d059737a9054aa014088" }
chashmap = { git = "https://gitlab.redox-os.org/ahornby/chashmap", rev = "901ace2ca3cdbc2095adb1af111d211e254e2aae" }
const-random = { git = "https://github.com/fbsource/const-random", rev = "374c5b46427fe2ffbf6acbd9c1687e0f1a809f95" }
curl = { git = "https://github.com/kulshrax/curl-rust", rev = "2a15bbd8dbbd54734313fa703a64db7ce6ddaff0" }
curl-sys = { git = "https://github.com/kulshrax/curl-rust", rev = "2a15bbd8dbbd54734313fa703a64db7ce6ddaff0" }
enumset = { git = "https://github.com/danobi/enumset", rev = "4c01c583c27a725948fededbfb3461c572a669a4" }
gotham-02 = { package = "gotham", git = "https://github.com/krallin/gotham-02.git", rev = "1eb3b976c31e7e4334b188f3abfa5cc2e5cae033" }
gotham_derive-02 = { package = "gotham_derive", git = "https://github.com/krallin/gotham-02.git", rev = "1eb3b976c31e7e4334b188f3abfa5cc2e5cae033" }
hyper-02 = { package = "hyper", version = "0.13.10", git = "https://github.com/krallin/hyper-02.git", rev = "9c9453c5ae3e92de4ba30edd81bb45371b8fa8d6" }
lru-disk-cache = { git = "https://github.com/mozilla/sccache", rev = "033ebaae69beeb0ac04e8c35d6ff1103487bd9a3" }
openssl = { git = "https://github.com/sfackler/rust-openssl", rev = "68fc8ba890d77986b06ca5ce29d1089285fbbcf9" }
openssl-sys = { git = "https://github.com/sfackler/rust-openssl", rev = "68fc8ba890d77986b06ca5ce29d1089285fbbcf9" }
petgraph = { git = "https://github.com/jkeljo/petgraph", rev = "e3e9dd8632d23973fdc0b42c1117d5e5fc5fa384" }
prost = { git = "https://github.com/gabrielrussoc/prost", branch = "protoc-runtime" }
prost-build = { git = "https://github.com/gabrielrussoc/prost", branch = "protoc-runtime" }
prost-derive = { git = "https://github.com/gabrielrussoc/prost", branch = "protoc-runtime" }
prost-types = { git = "https://github.com/gabrielrussoc/prost", branch = "protoc-runtime" }
r2d2_sqlite = { git = "https://github.com/jsgf/r2d2-sqlite.git", rev = "6d77a828ca0a3c507a3f58561532a1b6c66c7918" }
rustfilt = { git = "https://github.com/jsgf/rustfilt.git", rev = "8141fa7f1caee562ee8daffb2ddeca3d1f0d36e5" }
tokio-02 = { package = "tokio", version = "0.2.25", git = "https://github.com/krallin/tokio.git", rev = "818f943db36e32b7c928351c32fe69ac913409f9" }
tokio-compat = { package = "tokio-compat", version = "0.1.6", git = "https://github.com/krallin/tokio-compat.git", rev = "c2330c2a0141353e467cc5861988daa2eae7cb54" }
tokio-core = { git = "https://github.com/bolinfest/tokio-core", rev = "5f37aa3c627d56ee49154bc851d6930f5ab4398f" }
toml = { git = "https://github.com/jsgf/toml-rs", branch = "dotted-table-0.5.7" }
