[package]
name = "repo_listener"
edition = "2018"
version = "0.1.0"
authors = ['Facebook']
license = "GPLv2+"
include = ["src/**/*.rs"]

[dependencies]
async_limiter = { path = "../../common/async_limiter" }
backsyncer = { path = "../../commit_rewriting/backsyncer" }
blobrepo = { path = "../../blobrepo" }
blobrepo_factory = { path = "../../blobrepo/factory" }
blobstore_factory = { path = "../../blobstore/factory" }
cache_warmup = { path = "../../cache_warmup" }
cmdlib = { path = "../../cmdlib" }
context = { path = "../context" }
derived_data = { path = "../../derived_data" }
hgproto = { path = "../../hgproto" }
hook_manager_factory = { path = "../../hooks/hook_manager_factory" }
hooks = { path = "../../hooks" }
hooks_content_stores = { path = "../../hooks/content-stores" }
limits = { path = "../../../../configerator/structs/scm/mononoke/loadshedding" }
live_commit_sync_config = { path = "../../commit_rewriting/live_commit_sync_config" }
load_limiter = { path = "../../load_limiter" }
mercurial_derived_data = { path = "../../derived_data/mercurial_derived_data" }
metaconfig_types = { path = "../../metaconfig/types" }
mononoke_types = { path = "../../mononoke_types" }
mutable_counters = { path = "../../mutable_counters" }
permission_checker = { path = "../../permission_checker" }
repo_client = { path = "../../repo_client" }
scribe_ext = { path = "../../common/scribe_ext" }
scuba_ext = { path = "../../common/scuba_ext" }
slog_ext = { path = "../../common/rust/slog_ext" }
sql_construct = { path = "../../common/sql_construct" }
sql_ext = { path = "../../common/rust/sql_ext" }
sshrelay = { path = "../../sshrelay" }
synced_commit_mapping = { path = "../../commit_rewriting/synced_commit_mapping" }
tunables = { path = "../../tunables" }
warm_bookmarks_cache = { path = "../../bookmarks/warm_bookmarks_cache" }
cached_config = { git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
cloned = { git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
failure_ext = { git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
fbinit = { git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
futures_ext = { git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
futures_stats = { git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
stats = { git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
time_ext = { git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
tracing = { git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
anyhow = "1.0"
bytes = { version = "0.4", features = ["serde"] }
futures = { version = "0.3.5", features = ["async-await", "compat"] }
futures-old = { package = "futures", version = "0.1" }
itertools = "0.8"
lazy_static = "1.0"
maplit = "1.0"
openssl = "0.10"
ratelimit_meter = "5"
slog = { version = "2.5", features = ["max_level_debug"] }
slog-kvfilter = "0.7"
slog-term = "2.4.2"
thiserror = "1.0"
tokio = { version = "=0.2.13", features = ["full"] }
tokio-codec = "0.1"
tokio-io = "0.1"
tokio-old = { package = "tokio", version = "0.1" }
tokio-openssl = "0.2"
tokio-timer = "0.2"
