[package]
name = "pyworkingcopy"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.20"
cpython = { version = "0.7", default-features = false }
cpython_ext = { path = "../../../../lib/cpython-ext", default-features = false }
pathmatcher = { path = "../../../../lib/pathmatcher" }
pypathmatcher = { path = "../pypathmatcher" }
pytreestate = { path = "../pytreestate" }
workingcopy = { path = "../../../../lib/workingcopy" }
