[package]
name = "sshrelay"
version = "0.0.1"
authors = ["Facebook"]
license = "GPLv2+"
edition = "2018"

[dependencies]
bytes = "0.4.5"
serde = "1.0.20"
serde_derive = "1.0.20"
serde_json = "1.0.21"
tokio-io = "0.1.4"
