name: Release - Homebrew macOS-arm64
'on':
  workflow_dispatch: null
  push:
    tags:
    - v*
    - test-release-*
jobs:
  build:
    runs-on: macos-13-xlarge
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Grant Access
      run: git config --global --add safe.directory "$PWD"
    - name: set-env SAPLING_VERSION
      shell: bash
      run: echo "SAPLING_VERSION=$(ci/tag-name.sh)" >> $GITHUB_ENV
    - name: Tap homebrew-core
      run: brew tap homebrew/core
    - name: Prepare build environment
      run: 'eden/scm/packaging/mac/prepare_formula.py \

        -t aarch64-apple-darwin \

        -r ${{ env.SAPLING_VERSION }} \

        -o $(brew --repository)/Library/Taps/homebrew/homebrew-core/Formula/s/sapling.rb'
    - name: Install and build Sapling bottle
      run: HOMEBREW_NO_INSTALL_FROM_API=1 HOMEBREW_FAIL_LOG_LINES=100 brew install --build-bottle sapling
    - name: Create Sapling bottle
      run: HOMEBREW_NO_INSTALL_FROM_API=1 brew bottle sapling
    - name: Rename bottle to some platform specific name
      run: mv sapling*ventura.bottle*.tar.gz sapling_${{ env.SAPLING_VERSION }}.arm64_ventura.bottle.tar.gz
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: macos-homebrew-arm64-bottle
        path: sapling*ventura.bottle*.tar.gz
  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Grant Access
      run: git config --global --add safe.directory "$PWD"
    - name: Download Artifact
      uses: actions/download-artifact@v3
      with:
        name: macos-homebrew-arm64-bottle
    - name: Create pre-release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      shell: bash
      run: bash ci/retry.sh bash ci/create-release.sh $(ci/tag-name.sh)
    - name: Upload Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      shell: bash
      run: bash ci/retry.sh gh release upload --clobber $(ci/tag-name.sh) sapling*ventura.bottle*.tar.gz
