[package]
name = "revset"
edition = "2018"
version = "0.1.0"
authors = ['Facebook']
license = "GPLv2+"
include = ["src/**/*.rs"]

[dependencies]
blobrepo_hg = { path = "../blobrepo/blobrepo_hg" }
changeset_fetcher = { path = "../blobrepo/changeset_fetcher" }
context = { path = "../server/context" }
mercurial_types = { path = "../mercurial/types" }
mononoke_types = { path = "../mononoke_types" }
reachabilityindex = { path = "../reachabilityindex" }
uniqueheap = { path = "../common/uniqueheap" }
cloned = { git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
futures_ext = { git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
anyhow = "1.0"
futures-old = { package = "futures", version = "0.1" }
futures-util = "0.3"
maplit = "1.0"
thiserror = "1.0"

[dev-dependencies]
blobrepo = { path = "../blobrepo" }
fixtures = { path = "../tests/fixtures" }
revset_test_helper = { path = "revset-test-helper" }
skiplist = { path = "../reachabilityindex/skiplist" }
async_unit = { git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
failure_ext = { git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
fbinit = { git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
ascii = "1.0"
futures = { version = "0.3", features = ["async-await", "compat"] }
quickcheck = "0.9"
rand = { version = "0.7", features = ["small_rng"] }
tokio = "0.1"
